apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-prod
nameSuffix: -prod
commonLabels:
  app: web
  env: production

bases:
  - ../../base

images:
  - name: web
    newName: zivgitlab.wwu.io/c_luel01/ps_efsd/web
    newTag: main

patches:
  - target:
      kind: Ingress
      name: web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: search-engine.space
