apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-dev
nameSuffix: -dev
commonLabels:
  app: web
  env: development

bases:
  - ../../base

images:
  - name: web
    newName: zivgitlab.wwu.io/c_luel01/ps_efsd/web
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.search-engine.space
